"""
PDF report exporter for env-scanner.

Generates a professional Security Audit Report from a ScanResult using the
reportlab library (https://www.reportlab.com/opensource/).

Public API
----------
    export_pdf(result, output_path, scanned_target)
"""

from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import List, Tuple

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    NextPageTemplate,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    KeepTogether,
)
from reportlab.platypus.flowables import HRFlowable

from .patterns import CRITICAL, WARNING
from .scanner import Finding, ScanResult


# ---------------------------------------------------------------------------
# Colour palette
# ---------------------------------------------------------------------------
_NAVY        = colors.HexColor("#0D233D")
_DARK_BLUE   = colors.HexColor("#20478A")
_CRITICAL    = colors.HexColor("#C00000")
_WARNING_COL = colors.HexColor("#BF9000")
_CLEAN       = colors.HexColor("#38761D")
_ROW_ALT     = colors.HexColor("#EBF1FA")
_BORDER      = colors.HexColor("#B4BED2")
_LIGHT_GREY  = colors.HexColor("#F5F5F5")
_TEXT        = colors.HexColor("#1E1E1E")
_WHITE       = colors.white


# ---------------------------------------------------------------------------
# Page dimensions / margins
# ---------------------------------------------------------------------------
PAGE_W, PAGE_H = A4           # 595.27 x 841.89 pt
MARGIN_L = MARGIN_R = 15 * mm
MARGIN_T = 22 * mm            # leave room for header bar
MARGIN_B = 18 * mm


# ---------------------------------------------------------------------------
# Header / footer drawn on every page canvas
# ---------------------------------------------------------------------------

def _draw_header(canvas, doc) -> None:
    """Navy banner across the top of each page."""
    canvas.saveState()
    canvas.setFillColor(_NAVY)
    canvas.rect(0, PAGE_H - 18 * mm, PAGE_W, 18 * mm, fill=1, stroke=0)
    canvas.setFont("Helvetica-Bold", 10)
    canvas.setFillColor(_WHITE)
    canvas.drawString(MARGIN_L, PAGE_H - 12 * mm, "Security Audit Report  •  env-scanner")
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(PAGE_W - MARGIN_R, PAGE_H - 12 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _draw_footer(canvas, doc) -> None:
    """Thin rule + footer text at bottom of each page."""
    canvas.saveState()
    canvas.setStrokeColor(_BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN_L, MARGIN_B - 4 * mm, PAGE_W - MARGIN_R, MARGIN_B - 4 * mm)
    canvas.setFont("Helvetica", 6.5)
    canvas.setFillColor(colors.HexColor("#787878"))
    canvas.drawCentredString(
        PAGE_W / 2,
        MARGIN_B - 10 * mm,
        "Generated by env-scanner  •  github.com/OrChetrit/env-scanner  "
        "•  CONFIDENTIAL – For internal use only",
    )
    canvas.restoreState()


def _on_page(canvas, doc) -> None:
    _draw_header(canvas, doc)
    _draw_footer(canvas, doc)


# ---------------------------------------------------------------------------
# Styles
# ---------------------------------------------------------------------------

def _build_styles():
    base = getSampleStyleSheet()
    styles = {}

    styles["title"] = ParagraphStyle(
        "title",
        parent=base["Title"],
        fontSize=22,
        textColor=_NAVY,
        spaceAfter=4,
        alignment=1,       # centre
        fontName="Helvetica-Bold",
    )
    styles["subtitle"] = ParagraphStyle(
        "subtitle",
        fontSize=9,
        textColor=colors.HexColor("#646464"),
        spaceAfter=12,
        alignment=1,
        fontName="Helvetica",
    )
    styles["section"] = ParagraphStyle(
        "section",
        fontSize=12,
        textColor=_DARK_BLUE,
        spaceBefore=8,
        spaceAfter=4,
        fontName="Helvetica-Bold",
    )
    styles["meta_label"] = ParagraphStyle(
        "meta_label",
        fontSize=8.5,
        textColor=_TEXT,
        fontName="Helvetica-Bold",
        spaceAfter=2,
    )
    styles["meta_value"] = ParagraphStyle(
        "meta_value",
        fontSize=8.5,
        textColor=_TEXT,
        fontName="Helvetica",
        spaceAfter=2,
    )
    styles["body"] = ParagraphStyle(
        "body",
        fontSize=8.5,
        textColor=_TEXT,
        fontName="Helvetica",
        spaceAfter=3,
    )
    styles["remediation_text"] = ParagraphStyle(
        "remediation_text",
        fontSize=8,
        textColor=_TEXT,
        fontName="Helvetica",
        spaceAfter=6,
        leftIndent=4,
    )
    return styles


# ---------------------------------------------------------------------------
# Summary stat boxes
# ---------------------------------------------------------------------------

def _stat_table(result: ScanResult) -> Table:
    """Return a 4-column table of stat boxes."""
    stats = [
        ("Total Findings", str(result.total_findings), _DARK_BLUE),
        ("Critical",       str(result.critical_count), _CRITICAL),
        ("Warnings",       str(result.warning_count),  _WARNING_COL),
        ("Clean Files",    str(len(result.clean_files)), _CLEAN),
    ]

    cells = []
    for label, value, colour in stats:
        cell_content = [
            Paragraph(f'<font size="18" color="{colour.hexval()}"><b>{value}</b></font>', _build_styles()["subtitle"]),
            Paragraph(f'<font size="7" color="#505050">{label}</font>', _build_styles()["subtitle"]),
        ]
        cells.append(cell_content)

    col_w = (PAGE_W - MARGIN_L - MARGIN_R) / 4

    t = Table([cells], colWidths=[col_w] * 4, rowHeights=[28 * mm])
    t.setStyle(TableStyle([
        ("BOX",         (0, 0), (-1, -1), 0.5, _BORDER),
        ("INNERGRID",   (0, 0), (-1, -1), 0.5, _BORDER),
        ("VALIGN",      (0, 0), (-1, -1), "MIDDLE"),
        ("BACKGROUND",  (0, 0), (-1, -1), _LIGHT_GREY),
        # Top colour bars per column
        ("LINEABOVE",   (0, 0), (0, 0), 3, _DARK_BLUE),
        ("LINEABOVE",   (1, 0), (1, 0), 3, _CRITICAL),
        ("LINEABOVE",   (2, 0), (2, 0), 3, _WARNING_COL),
        ("LINEABOVE",   (3, 0), (3, 0), 3, _CLEAN),
    ]))
    return t


# ---------------------------------------------------------------------------
# Meta info table
# ---------------------------------------------------------------------------

def _meta_table(scan_date: str, target: str, files_scanned: int) -> Table:
    s = _build_styles()
    rows = [
        [Paragraph("<b>Scan Date</b>", s["meta_label"]),  Paragraph(scan_date, s["meta_value"])],
        [Paragraph("<b>Target</b>",    s["meta_label"]),  Paragraph(target,    s["meta_value"])],
        [Paragraph("<b>Files Scanned</b>", s["meta_label"]), Paragraph(str(files_scanned), s["meta_value"])],
    ]
    col_w = PAGE_W - MARGIN_L - MARGIN_R
    t = Table(rows, colWidths=[38 * mm, col_w - 38 * mm])
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING",    (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ]))
    return t


# ---------------------------------------------------------------------------
# Findings table
# ---------------------------------------------------------------------------

def _severity_cell(severity: str) -> Paragraph:
    """Return a coloured severity badge paragraph."""
    colour = _CRITICAL if severity == CRITICAL else (_WARNING_COL if severity == WARNING else _CLEAN)
    style = ParagraphStyle(
        "sev",
        fontSize=7,
        textColor=_WHITE,
        fontName="Helvetica-Bold",
        alignment=1,
        backColor=colour,
        borderPad=2,
    )
    return Paragraph(severity.upper(), style)


def _findings_table(findings: List[Finding]) -> Table:
    """Build the full findings detail table."""
    col_w = PAGE_W - MARGIN_L - MARGIN_R   # 165 mm
    # Column widths: #, Line, Variable, Secret Type, Severity
    widths = [
        10 * mm,   # #
        14 * mm,   # Line
        46 * mm,   # Variable
        62 * mm,   # Secret Type
        33 * mm,   # Severity
    ]

    s = _build_styles()

    def _hdr(text: str) -> Paragraph:
        return Paragraph(
            f'<font color="white"><b>{text}</b></font>',
            ParagraphStyle("th", fontSize=8, fontName="Helvetica-Bold", alignment=1),
        )

    header = [_hdr("#"), _hdr("Line"), _hdr("Variable"), _hdr("Secret Type"), _hdr("Severity")]
    rows = [header]

    for i, f in enumerate(findings, start=1):
        var_name = (f.variable_name[:30] + "…") if len(f.variable_name) > 30 else f.variable_name
        stype    = (f.secret_type[:40] + "…")    if len(f.secret_type)    > 40 else f.secret_type
        bg = _ROW_ALT if i % 2 == 0 else _WHITE
        rows.append([
            Paragraph(str(i),           ParagraphStyle("td_c", fontSize=8, fontName="Helvetica", alignment=1)),
            Paragraph(str(f.line_number), ParagraphStyle("td_c", fontSize=8, fontName="Helvetica", alignment=1)),
            Paragraph(var_name,          ParagraphStyle("td",   fontSize=8, fontName="Helvetica")),
            Paragraph(stype,             ParagraphStyle("td",   fontSize=8, fontName="Helvetica")),
            _severity_cell(f.severity),
        ])

    t = Table(rows, colWidths=widths, repeatRows=1)

    # Base style
    style_cmds = [
        ("BACKGROUND",    (0, 0), (-1, 0),  _NAVY),
        ("TEXTCOLOR",     (0, 0), (-1, 0),  _WHITE),
        ("GRID",          (0, 0), (-1, -1), 0.25, _BORDER),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING",   (0, 0), (-1, -1), 4),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 4),
    ]
    # Alternating row backgrounds
    for i in range(1, len(rows)):
        bg = _ROW_ALT if i % 2 == 0 else _WHITE
        style_cmds.append(("BACKGROUND", (0, i), (-1, i), bg))

    t.setStyle(TableStyle(style_cmds))
    return t


# ---------------------------------------------------------------------------
# Remediation appendix
# ---------------------------------------------------------------------------

def _remediation_flowables(findings: List[Finding]) -> list:
    s = _build_styles()
    flowables: list = [
        PageBreak(),
        Paragraph("Remediation Guide", s["section"]),
        HRFlowable(width="100%", thickness=0.5, color=_DARK_BLUE, spaceAfter=6),
    ]

    seen: set = set()
    for f in findings:
        if f.secret_type in seen:
            continue
        seen.add(f.secret_type)

        colour = _CRITICAL if f.severity == CRITICAL else _WARNING_COL
        badge_style = ParagraphStyle(
            "badge",
            fontSize=9,
            fontName="Helvetica-Bold",
            textColor=_WHITE,
            backColor=colour,
            borderPad=3,
            spaceAfter=3,
        )
        flowables.append(
            KeepTogether([
                Paragraph(f"{f.secret_type}  [{f.severity.upper()}]", badge_style),
                Paragraph(f.remediation, s["remediation_text"]),
            ])
        )

    return flowables


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def export_pdf(result: ScanResult, output_path: str | Path, scanned_target: str) -> None:
    """
    Generate a professional PDF Security Audit Report from *result*.

    Parameters
    ----------
    result:
        The ScanResult produced by the scanner.
    output_path:
        Destination file path for the PDF (e.g. ``"report.pdf"``).
    scanned_target:
        Human-readable description of what was scanned (file path or directory).
    """
    output_path = Path(output_path)
    scan_date = date.today().strftime("%B %d, %Y")
    s = _build_styles()

    # ------------------------------------------------------------------
    # Document template with custom header/footer on every page
    # ------------------------------------------------------------------
    usable_w = PAGE_W - MARGIN_L - MARGIN_R
    frame = Frame(MARGIN_L, MARGIN_B, usable_w, PAGE_H - MARGIN_T - MARGIN_B, id="main")
    template = PageTemplate(id="standard", frames=[frame], onPage=_on_page)
    doc = BaseDocTemplate(
        str(output_path),
        pagesize=A4,
        pageTemplates=[template],
        leftMargin=MARGIN_L,
        rightMargin=MARGIN_R,
        topMargin=MARGIN_T,
        bottomMargin=MARGIN_B,
    )

    # ------------------------------------------------------------------
    # Build story (content)
    # ------------------------------------------------------------------
    story: list = []

    # Title block
    story.append(Paragraph("Security Audit Report", s["title"]))
    story.append(Paragraph(f"Generated by env-scanner  •  {scan_date}", s["subtitle"]))
    story.append(HRFlowable(width="100%", thickness=1, color=_NAVY, spaceAfter=10))

    # Scan meta info
    story.append(Paragraph("Scan Summary", s["section"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=_DARK_BLUE, spaceAfter=4))
    story.append(_meta_table(scan_date, scanned_target, len(result.files_scanned)))
    story.append(Spacer(1, 6 * mm))
    story.append(_stat_table(result))
    story.append(Spacer(1, 8 * mm))

    # Findings table
    story.append(Paragraph("Detailed Findings", s["section"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=_DARK_BLUE, spaceAfter=4))

    if not result.findings:
        story.append(
            Paragraph(
                '<font color="#38761D"><b>✔  No secrets detected. All scanned files appear clean.</b></font>',
                s["body"],
            )
        )
    else:
        story.append(_findings_table(result.findings))
        story.append(Spacer(1, 4 * mm))
        story.append(
            Paragraph(
                f"<i>Total: {result.total_findings} finding(s)  —  "
                f"{result.critical_count} critical, {result.warning_count} warning(s).</i>",
                ParagraphStyle("note", fontSize=8, textColor=colors.HexColor("#646464"), fontName="Helvetica-Oblique"),
            )
        )
        story.extend(_remediation_flowables(result.findings))

    doc.build(story)
